title: Digital Trend Centar
author: JELJDTC
email: info@digitaltrendcenter.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Transfomation is our creed, we believe in the power of innovation and we are always looking
  the way to make things easier and better.
theme: minima
# social links
twitter_username: your-twitter-handle digitaltrendcenter
github_username:  your-github-handle JELJDTC
show_excerpts: true # set to false to remove excerpts on the homepage
